import Footer from "@/Layout/Footer/Footer"
import Navbar from "@/Layout/Navbar/Navbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <Navbar />
      <body>{children}</body>
      <Footer />
    </html>
  )
}
